package functions.sockets.internal.errors

class RequestFailedException(cause: Throwable) extends RuntimeException(cause)
